Faraday		:	Astrophys.o DiffEq.o ExtMath.o getparms.o GS.o IDLInterface.o Messages.o MWMain.o Std_DF.o Transfer.o
			g++ -shared -o MWTransfer.so Astrophys.o DiffEq.o ExtMath.o getparms.o GS.o IDLInterface.o Messages.o MWMain.o Std_DF.o Transfer.o
Astrophys.o	:	Astrophys.cpp Astrophys.h DF.h DiffEq.h ExtMath.h GS.h IDLInterface.h Messages.h MWMain.h Std_DF.h Transfer.h
			g++ -c -O3 -fPIC Astrophys.cpp
DiffEq.o	:	DiffEq.cpp Astrophys.h DF.h DiffEq.h ExtMath.h GS.h IDLInterface.h Messages.h MWMain.h Std_DF.h Transfer.h
			g++ -c -O3 -fPIC DiffEq.cpp
ExtMath.o	:	ExtMath.cpp Astrophys.h DF.h DiffEq.h ExtMath.h GS.h IDLInterface.h Messages.h MWMain.h Std_DF.h Transfer.h
			g++ -c -O3 -fPIC ExtMath.cpp
getparms.o	:	getparms.cpp Astrophys.h DF.h DiffEq.h ExtMath.h GS.h IDLInterface.h Messages.h MWMain.h Std_DF.h Transfer.h
			g++ -c -O3 -fPIC getparms.cpp
GS.o		:	GS.cpp Astrophys.h DF.h DiffEq.h ExtMath.h GS.h IDLInterface.h Messages.h MWMain.h Std_DF.h Transfer.h
			g++ -c -O3 -fPIC GS.cpp
IDLInterface.o	:	IDLInterface.cpp Astrophys.h DF.h DiffEq.h ExtMath.h GS.h IDLInterface.h Messages.h MWMain.h Std_DF.h Transfer.h
			g++ -c -O3 -fPIC IDLInterface.cpp
Messages.o	:	Messages.cpp Astrophys.h DF.h DiffEq.h ExtMath.h GS.h IDLInterface.h Messages.h MWMain.h Std_DF.h Transfer.h
			g++ -c -O3 -fPIC Messages.cpp
MWMain.o	:	MWMain.cpp Astrophys.h DF.h DiffEq.h ExtMath.h GS.h IDLInterface.h Messages.h MWMain.h Std_DF.h Transfer.h
			g++ -c -O3 -fPIC MWMain.cpp
Std_DF.o	:	Std_DF.cpp Astrophys.h DF.h DiffEq.h ExtMath.h GS.h IDLInterface.h Messages.h MWMain.h Std_DF.h Transfer.h
			g++ -c -O3 -fPIC Std_DF.cpp
Transfer.o	:	Transfer.cpp Astrophys.h DF.h DiffEq.h ExtMath.h GS.h IDLInterface.h Messages.h MWMain.h Std_DF.h Transfer.h
			g++ -c -O3 -fPIC Transfer.cpp