;+
; Returns an array of structs (one per a,b). Legacy image tags are always present.
; Independent Q searches of RES2 and CHI2 (default apply2=3) until both are done.
; Spectrum mode: ROI-integrated metrics from gx_maps2spectrum / gx_metrics_spectrum
; (RES2 = res2_norm, CHI2 uses S_sdev). Image ROI uses mask= (legacy rules;
; default levels[0]). Spectrum mode: full ref set always; inclusion/weighting
; via spec_weights= only (omit → all channels weight 1). Image mode: scalar
; chan= or freq= only. Stores search-subset spectra (spec_axis where w>0) and
; full ROI spectra (spec_axis_all, …) — see gx_processmodels_ebtel.
; To display one spectrum channel with legacy plotters/GUI, use
; gx_result_select_channel.
;
; At the end of a successful search, Best of Bests.ps is generated by default
; (plot_best=1). Per-cell set_a*b*_final.ps are written during the search;
; they are NOT rewritten by Best of Bests unless /replot_final is passed
; through _extra (or to gx_plotbestchmpmodels_ebtel). Pass plot_best=0 to skip BoB.
;-
function gx_search4bestq, gxmpath=gxmpath,a_arr=a_arr,b_arr=b_arr,q_start=q_start, $
                     modDir=modDir,psDir=psDir,tmpDir=tmpDir,refdatapath=refdatapath,$
                     ebtel_path=ebtel_path,renderer=renderer,info=info,$
                     xc=xc,yc=yc,xfov=xfov,yfov=yfov,nx=nx,ny=ny,$
                     levels=levels,mask=mask,resize=resize,save_gxc=save_gxc,redo=redo,$
                     save_result=save_result,plot_best=plot_best,freq=freq,chan=chan,$
                     search_mode=search_mode,spec_freq=spec_freq,spec_chan=spec_chan,$
                     chmp_ref=chmp_ref,nobackground=nobackground,spec_weights=spec_weights,$
                     _extra=_extra
  final_result=[]
  catch, error_status
  if error_status ne 0 then begin
    catch, /cancel
    gx_message,!error_state.msg + ' ' + !error_state.sys_msg
    result=final_result
    return, result
  endif
  ;+++++++++++++++++++++++++++++++++++++++++++
  default,levels,[12,20,30,50,80]
  ; Best of Bests after the search unless off (does not rewrite cell finals)
  default,plot_best,1
  ;default,resize,100
  ;++++++++++++++++++++++++++++++++++++++++++++
  default,a_arr,[0.5,0.75,1,1.25,1.5]
  default,b_arr,[0.5,0.75,1,1.25,1.5]
  ;++++++++++++++++++++++++++++++++++++++++++++
  default,q_start,[0.0001,0.001]
  ;++++++++++++++++++++++++++++++++++++++++++++
  default,xc,-86.68
  default,yc,-320.0
  default,xfov,200.0
  default,yfov,200.0
  default,nx,200
  default,ny,200
  ;++++++++++++++++++++++++++++++++++++++++++++
  default,modDir,curdir()+path_sep()+'modDir'
  default,psDir,curdir()+path_sep()+'psDir'
  default,tmpDir,curdir()+path_sep()+'tmpDir'
  ;++++++++++++++++++++++++++++++++++++++++++++++
  default,ebtel_path, gx_findfile('ebtel.sav',folder='')
  ;+++++++++++++++++++++++++++++++++++++++++++++
  default,renderer,gx_findfile((!version.os_family eq 'Windows')?'AR_GRFF_nonLTE.pro':'grffdemtransfer.pro',folder='')
  ;+++++++++++++++++++++++++++++++++++++++++++++
  default,search_mode,'image'
  search_mode=strlowcase(strcompress(search_mode,/rem))
  spectrum_mode=search_mode eq 'spectrum'
  all_refs=!null
  ;
; Frequency / channel / weight roles (mutually exclusive by mode):
;   Image mode:
;     freq= (MW) or chan= (EUV) selects ONE reference axis — must be a scalar.
;     Vector chan=/freq= is refused here (future: loop/bridges over the list).
;     spec_weights= is refused.
;     Optional chmp_ref= skips reload when the caller already selected one object.
;   Spectrum mode:
;     Always loads the full reference set (all channels / freqs in refdatapath).
;     Channel/frequency inclusion and soft emphasis use spec_weights= only
;     (omit → uniform weight 1 on every ref axis). w<=0 excludes a point from
;     RES2/CHI2; w>0 is "in search" for plots/stored S_obs.
;     Top-level chan=, freq=, spec_chan=, spec_freq= are refused.
;     MW synthesis frequencies still come from _extra.freqlist when needed.
;
; Spectrum mode: REF and ALL_REFS are the full ref set. processmodels applies
; spec_weights on the ROI-integrated spectrum and stores search-subset spectra
; for axes with w>0.
;
  mw_mode=0b
  if spectrum_mode then begin
    ;----- refuse image-only selectors -----
    if n_elements(chan) gt 0 or n_elements(freq) gt 0 or $
       n_elements(spec_chan) gt 0 or n_elements(spec_freq) gt 0 then $
      message,'search_mode=spectrum: use spec_weights= to include/exclude or weight channels; ' + $
        'chan=, freq=, spec_chan=, and spec_freq= are only valid for search_mode=image'

    if isa(_extra,'STRUCT') and tag_exist(_extra,'freqlist') then begin
      synth_freq=double(_extra.freqlist)
      mw_mode=1b
    endif

    ; Same ref loader as image mode: full objarr of CHMP map objects
    all_refs=gx_ref2chmp(refdatapath,err_msg=err_msg,_extra=_extra)
    if size(all_refs,/tname) ne 'OBJREF' then $
      message,'Failed to load reference maps via gx_ref2chmp: '+ $
        (size(err_msg,/tname) eq 'STRING'?strjoin(err_msg,' '):'unknown error')

    ; Full axis always — selection is spec_weights only
    ref=gx_ref_select_axis(all_refs,err_msg=err_msg,is_chan=spec_is_chan,axis=spec_axis)
    if size(ref,/tname) ne 'OBJREF' then $
      message,'Failed to build spectrum reference axis: '+ $
        (size(err_msg,/tname) eq 'STRING'?strjoin(err_msg,' '):'unknown error')
    if n_elements(ref) lt 2 then $
      message,'search_mode=spectrum needs at least two reference channels/frequencies'

    if n_elements(spec_weights) gt 0 then begin
      if n_elements(spec_weights) ne n_elements(ref) then $
        message,'spec_weights length ('+strtrim(n_elements(spec_weights),2)+ $
          ') must equal the number of reference axes ('+strtrim(n_elements(ref),2)+ $
          '), in gx_ref2chmp order (sorted by chan/freq): ['+ $
          strjoin(strtrim(string(spec_axis,format='(g0)'),2),', ')+']'
      if n_elements(all_refs) ne n_elements(ref) then $
        message,'Internal error: spectrum ref axis count ('+strtrim(n_elements(ref),2)+ $
          ') differs from loaded all_refs ('+strtrim(n_elements(all_refs),2)+')'
      if total(double(spec_weights) gt 0d) lt 1 then $
        message,'spec_weights must have at least one positive entry'
    endif

    if mw_mode then begin
      if isa(_extra,'STRUCT') then begin
        if tag_exist(_extra,'freqlist') then _extra.freqlist=synth_freq $
        else _extra=create_struct(_extra,'freqlist',synth_freq)
      endif else _extra={freqlist:synth_freq}
    endif
    message,string(n_elements(ref), $
      (n_elements(spec_weights) gt 0)?total(double(spec_weights) gt 0):n_elements(ref), $
      format="('Spectrum refs: ',i0,' full / ',i0,' with positive weight')"),/info
    ref_geom=ref[0]
  endif else begin
    ;----- image mode: refuse spectrum-only weights -----
    if n_elements(spec_weights) gt 0 then $
      message,'search_mode=image: spec_weights= is only valid for search_mode=spectrum'
    if n_elements(spec_chan) gt 0 or n_elements(spec_freq) gt 0 then $
      message,'search_mode=image: use chan= or freq= (scalar); spec_chan=/spec_freq= are not used'

    ; Image mode: one CHMP ref object per search (single freq or chan).
    if size(chmp_ref, /tname) eq 'OBJREF' and obj_valid(chmp_ref) then begin
      ref = chmp_ref
      ref_geom = ref
      mw_mode = n_elements(freq) gt 0
      all_refs = !null
    endif else begin
      all_refs = gx_ref2chmp(refdatapath, err_msg=err_msg, _extra=_extra)
      if size(all_refs, /tname) ne 'OBJREF' then $
        message, 'Failed to load reference maps via gx_ref2chmp: '+ $
          (size(err_msg, /tname) eq 'STRING' ? strjoin(err_msg, ' ') : 'unknown error')
      if n_elements(freq) gt 0 and n_elements(chan) gt 0 then $
        message, 'search_mode=image: specify only one of freq= or chan=, not both'
      if n_elements(freq) gt 1 then $
        message, 'search_mode=image: freq= must be a scalar (vector image searches not implemented yet)'
      if n_elements(chan) gt 1 then $
        message, 'search_mode=image: chan= must be a scalar (vector image searches not implemented yet)'

      ; Probe ref axis type before selection (CHAN vs FREQ must match keyword)
      _probe = gx_ref_select_axis(all_refs, err_msg=em_probe, is_chan=refs_are_chan, axis=all_axis)
      if size(_probe, /tname) ne 'OBJREF' then $
        message, 'Failed to inspect reference axes: '+ $
          (size(em_probe, /tname) eq 'STRING' ? strjoin(em_probe, ' ') : 'unknown error')
      if keyword_set(refs_are_chan) then begin
        if n_elements(freq) gt 0 then $
          message, 'search_mode=image: reference set is CHAN (EUV); use scalar chan=, not freq=. Available: ['+ $
            strjoin(strtrim(string(all_axis, format='(g0)'), 2), ', ')+']'
        if n_elements(chan) eq 0 and n_elements(all_refs) gt 1 then $
          message, 'search_mode=image: specify scalar chan= to select one of ['+ $
            strjoin(strtrim(string(all_axis, format='(g0)'), 2), ', ')+']'
      endif else begin
        if n_elements(chan) gt 0 then $
          message, 'search_mode=image: reference set is FREQ (MW); use scalar freq=, not chan=. Available: ['+ $
            strjoin(strtrim(string(all_axis, format='(g0)'), 2), ', ')+'] GHz'
        if n_elements(freq) eq 0 and n_elements(all_refs) gt 1 then $
          message, 'search_mode=image: specify scalar freq= to select one of ['+ $
            strjoin(strtrim(string(all_axis, format='(g0)'), 2), ', ')+'] GHz'
      endelse

      if n_elements(freq) eq 1 or n_elements(chan) eq 1 then begin
        ref = gx_ref_select_axis(all_refs, freq=freq, chan=chan, err_msg=err_msg, $
          is_chan=sel_is_chan, axis=sel_axis)
      endif else if n_elements(all_refs) eq 1 then begin
        ref = all_refs[0]
        sel_axis = all_axis
      endif else $
        message, 'search_mode=image: specify scalar freq= or chan= to select one reference channel'
      if size(ref, /tname) ne 'OBJREF' then $
        message, 'Requested '+ $
          ((n_elements(chan) gt 0) ? 'chan='+strtrim(string(chan[0], format='(g0)'), 2) : $
            'freq='+strtrim(string(freq[0], format='(g0)'), 2)) + $
          ' not found in reference set ['+ $
          strjoin(strtrim(string(all_axis, format='(g0)'), 2), ', ')+']: '+ $
          (size(err_msg, /tname) eq 'STRING' ? strjoin(err_msg, ' ') : 'unknown error')
      if n_elements(ref) gt 1 then $
        message, 'search_mode=image: reference selection returned multiple axes; use scalar freq=/chan='
      ; Explicit consistency: selected axis must match the request
      if n_elements(chan) eq 1 then begin
        if abs(double(sel_axis[0]) - double(chan[0])) gt ((1d-3*abs(double(chan[0]))) > 1d-6) then $
          message, string(chan[0], sel_axis[0], $
            format="('Image chan= inconsistency: requested ',g0,' but selected ref chan=',g0)")
      endif
      if n_elements(freq) eq 1 then begin
        if abs(double(sel_axis[0]) - double(freq[0])) gt ((1d-3*abs(double(freq[0]))) > 1d-6) then $
          message, string(freq[0], sel_axis[0], $
            format="('Image freq= inconsistency: requested ',g0,' but selected ref freq=',g0)")
      endif
      ref_geom = ref
      mw_mode = n_elements(freq) gt 0
      all_refs = !null
    endelse
  endelse
  ;+++++++++++++++++++++++++++++++++++++++++++++
  if not file_test(modDir) then file_mkdir,modDir
  if keyword_set(save_gxc) then begin
    gxcDir=modDir+path_sep()+'gxc'
    if not file_test(gxcDir) then file_mkdir,gxcDir
  end
  if not file_test(psDir) then file_mkdir,psDir
  
  map=obj_new('map')
  for ii=0,n_elements(a_arr)-1 do begin
  for jj=0,n_elements(b_arr)-1 do begin
      ;+++++++++++++++++++++++++++++++++++++
     a=a_arr[ii]
     b=b_arr[jj]
     q=q_start
     t0=systime(/s)
     done=0b
     almost_done=0
     done_res=0b
     done_chi=0b
     default,apply2,3
     force_done=0
     if ~spectrum_mode and n_elements(freq) ne 0 then begin
       if isa(_extra,'STRUCT') then begin
         if ~tag_exist(_extra,'f_min') then _extra=create_struct(_extra,'f_min',freq*1d9)
         if ~tag_exist(_extra,'n_freq') then _extra=create_struct(_extra,'n_freq',1)
       endif else _extra={f_min:freq*1d9,n_freq:1}
     endif
     counter=0
     REPEAT BEGIN; until done       
        for j=0,n_elements(q)-1 do begin
          modfile=modDir+path_sep()+strcompress(string(a,b,q[j],format="('i_a',f7.2,'b',f7.2,'q',g0,'.map')"),/rem)
          if ~file_exist(modfile) or keyword_set(redo)then begin
            if ~isa(model,'gxmodel') then begin
              model=gx_read(gxmpath)
              (model->Corona())->SetProperty,ignore=keyword_set(nobackground)
              fovdata=model->SetFOV(b0=ref_geom->get(/b0),l0=ref_geom->get(/l0),rsun=ref_geom->get(/rsun),$
                                    xc=xc,yc=yc,xfov=xfov, yfov=yfov,nx=nx,ny=ny,/compute_grid,_extra=_extra)
              end
            if tag_exist(_extra,'q0_formula') then q0_formula=_extra.q0_formula
            default,q0_formula,'q[0]'
            q_formula=string(a,b,format="('q0*(B/q[1])^(',g0,')/(L/q[2])^(',g0,')')")
            q_parms=[q[j], 100.0, 1.0000000d+009, 0.0, 0.0]
            if keyword_set(mw_mode) or (n_elements(freq) gt 0) or $
               (isa(_extra,'STRUCT') and tag_exist(_extra,'freqlist')) then begin
             map=gx_mwrender_ebtel(model,renderer,info=info,ebtel_path=ebtel_path,$
                 q_parms=q_parms,q_formula=q_formula,q0_formula=q0_formula,$
                 gxcube=gxcube,_extra=_extra)
            endif else begin
              map=gx_euvrender_ebtel(model,renderer,info=info,ebtel_path=ebtel_path,$
                q_parms=q_parms,q_formula=q_formula,q0_formula=q0_formula,$
                gxcube=gxcube,/all,_extra=_extra)
            endelse
            if obj_valid(map) then begin
                save,map,file=modfile
                obj_destroy,map
            endif
            if (isa(gxcube) and keyword_set(save_gxc)) then begin
              if n_elements(synth_freq) gt 0 then $
                save,gxcube,file=gxcDir+path_sep()+strcompress(string(a,b,q[j],synth_freq[0],format="('a',f7.2,'b',f7.2,'q',g0,'-',g0,' GHz.gxc')"),/rem) $
              else if n_elements(freq) gt 0 then $
                save,gxcube,file=gxcDir+path_sep()+strcompress(string(a,b,q[j],freq[0],format="('a',f7.2,'b',f7.2,'q',g0,'-',g0,' GHz.gxc')"),/rem)
              if n_elements(chan) gt 0 then save,gxcube,file=gxcDir+path_sep()+strcompress(string(a,b,q[j],chan[0],format="('a',f7.2,'b',f7.2,'q',g0,'-',g0,' A.gxc')"),/rem)
            endif
          endif else gx_message, modfile+' already exists, no reprocessing requested!',/info
        endfor
        result=gx_processmodels_ebtel(ab=[a,b],ref=ref,all_refs=all_refs,$
          modDir=modDir,psDir=psDir,$
          levels=levels,mask=mask,resize=resize,$
          file_arr=file_arr,apply2=apply2,done=force_done,$
          search_mode=search_mode,spec_weights=spec_weights,$
          refdatapath=refdatapath,gxmpath=gxmpath,q_start=q_start,counter=counter,_extra=_extra)
        if size(result,/tname) eq 'STRUCT' then begin
          add_q=(apply2 eq 1)?((result.res2_done eq 0) and (result.chi2_done  eq 0)):((result.res2_done eq 0) or (result.chi2_done  eq 0))
          if add_q eq 1 then begin
            nq=n_elements(q)
            if apply2 eq 1 then begin
              if result.res2_done eq 0 then q=[q,result.q_res2_best] else q=[q,result.q_chi2_best]
            endif else begin
              q=[q,result.q_res2_best,result.q_chi2_best]
            endelse
            q=q[uniq(q,sort(q))]
            q=q[where(finite(q) eq 1)]
            if n_elements(q) eq nq then begin
              if apply2 eq 1 then apply2=3 else force_done=1
            endif
          endif else if apply2 eq 3 then done=1 else apply2=3
        endif else done=1
     ENDREP UNTIL done
     final_result=[final_result,result]   
 endfor
 endfor
 gx_message, string(n_elements(a_arr)*n_elements(b_arr),(systime(/s)-t0)/3600,format="('Computed ',i2,' sets in ',g0,' hours')"),/info
 obj_destroy,map
 result=final_result
 if size(save_result,/tname) eq 'STRING' then save,result,file=strcompress(tmpDir+path_sep()+save_result)
 if keyword_set(plot_best) then begin
   if size(result,/tname) eq 'STRUCT' then $
     gx_plotbestchmpmodels_ebtel, result, psDir, levels=levels, _extra=_extra $
   else message,'plot_best requested but no result structure to plot.',/info
 endif
 return,result
 end
